#!/usr/bin/env python3
"""Working example: Substitute symbolic solution into an equation.

Usage:

    Linux / macOS / WSL / Git Bash:
        python3 solved-substitute.py equations.json solutions.json > output.tex

    Windows PowerShell:
        py -3.12 -X utf8 solved-substitute.py equations.json solutions.json | Set-Content -Encoding UTF8 output.tex

Notes:
    - Reads the original equations JSON.
    - Reads solutions JSON generated by equations-solve.py.
    - Substitutes the first solution into the expression.
    - Outputs the evaluated expression as TeX.
"""

import json
import sys

import sympy as sp
from sympy.parsing.latex import parse_latex


if len(sys.argv) != 3:
    raise SystemExit(
        "Usage: solved-substitute.py equations.json solutions.json"
    )

equations_file = sys.argv[1]
solutions_file = sys.argv[2]

with open(equations_file) as f:
    equations = json.load(f)

with open(solutions_file) as f:
    solutions = json.load(f)


expr = parse_latex(
    equations["equations"][0]["valueTex"]
)

variable = sp.Symbol(
    solutions["variable"]
)

if not solutions["solutions"]:
    raise SystemExit("No solutions available.")

solution = parse_latex(
    solutions["solutions"][0]
)

result = sp.simplify(
    expr.subs(variable, solution)
)

print(sp.latex(result))